# -*- coding: utf-8 -*-
"""dashboard_fakultas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11xf_vVQjNG5z7L5GXIIQudYKscf43NAf
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

st.set_page_config(layout="wide")
st.title("Dashboard Fakultas Universitas")

# Load Excel
xlsx = pd.ExcelFile("data_dashboard.xlsx")

# Baca semua sheet
df_aktif = pd.read_excel(xlsx, "Mahasiswa Aktif")
df_lulusan = pd.read_excel(xlsx, "Lulusan per Semester")
df_waktu = pd.read_excel(xlsx, "Waktu Tempuh Studi")
df_akreditasi = pd.read_excel(xlsx, "Status Akreditasi")
df_prodi = pd.read_excel(xlsx, "Prodi Aktif")
df_distribusi = pd.read_excel(xlsx, "Distribusi Mahasiswa")
df_kuesioner = pd.read_excel(xlsx, "Kuesioner Dosen")

# Sidebar: filter tahun
tahun_opsi = sorted(df_aktif["Tahun"].dropna().unique())
tahun_pilih = st.sidebar.selectbox("Pilih Tahun", tahun_opsi)

# === Mahasiswa Aktif ===
st.subheader("Jumlah Mahasiswa Aktif per Program Studi")
aktif = df_aktif[df_aktif["Tahun"] == tahun_pilih]
st.bar_chart(data=aktif, x="Program Studi", y="Jumlah Mahasiswa")

# === Lulusan per Semester ===
st.subheader("Jumlah Lulusan per Semester")
lulusan = df_lulusan[df_lulusan["Tahun"] == tahun_pilih]
st.line_chart(data=lulusan, x="Program Studi", y="Jumlah Lulusan")

# === Waktu Tempuh Studi ===
st.subheader("Rata-rata Waktu Tempuh Studi (Tahun)")
st.dataframe(df_waktu)

# === Status Akreditasi ===
st.subheader("Status Akreditasi Program Studi")
st.dataframe(df_akreditasi)

# === Jumlah Prodi Aktif ===
st.subheader("Jumlah Program Studi Aktif per Jenjang")
st.bar_chart(data=df_prodi, x="Jenjang", y="Jumlah Prodi Aktif")

# === Distribusi Mahasiswa ===
st.subheader("Distribusi Mahasiswa per Jenjang dan Tahun")
distribusi = df_distribusi[df_distribusi["Tahun"] == tahun_pilih]
st.bar_chart(data=distribusi, x="Jenjang", y="Jumlah Mahasiswa")

# === Kuesioner Dosen ===
st.subheader("Rata-rata Skor Penilaian Dosen oleh Mahasiswa")
kues = df_kuesioner[df_kuesioner["Tahun"] == tahun_pilih]
st.bar_chart(data=kues, x="Program Studi", y="Rata-rata Skor Penilaian Dosen (1-5)")

st.caption("Sumber data: Simulasi internal")
