# -*- coding: utf-8 -*-
"""dashboard_fakultas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11xf_vVQjNG5z7L5GXIIQudYKscf43NAf
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px


st.set_page_config(layout="wide")
st.title("Dashboard  Fakultas Sains dan Teknologi Universitas Kartama")

# Load Excel
xlsx = pd.ExcelFile("data_dashboard.xlsx")

# Baca semua sheet
df_aktif = pd.read_excel(xlsx, "Mahasiswa Aktif")
df_lulusan = pd.read_excel(xlsx, "Lulusan per Semester")
df_waktu = pd.read_excel(xlsx, "Waktu Tempuh Studi")
df_akreditasi = pd.read_excel(xlsx, "Status Akreditasi")
df_prodi = pd.read_excel(xlsx, "Prodi Aktif")
df_distribusi = pd.read_excel(xlsx, "Distribusi Mahasiswa")
df_kuesioner = pd.read_excel(xlsx, "Kuesioner Dosen")

# Sidebar: filter tahun
tahun_opsi = sorted(df_aktif["Tahun"].dropna().unique())
tahun_pilih = st.sidebar.selectbox("Pilih Tahun", tahun_opsi)

# Sidebar: filter prodi
prodi_opsi = sorted(df_aktif["Program Studi"].dropna().unique())
prodi_pilih = st.sidebar.selectbox("Pilih Program Studi", ["Semua"] + prodi_opsi)

# === KPI Boxes ===
st.markdown("## Ringkasan Data")

# Siapkan tahun sebelumnya untuk perbandingan
tahun_sebelumnya = tahun_pilih - 1

col1, col2, col3 = st.columns(3)

# --- Mahasiswa Aktif ---
aktif_now = df_aktif[df_aktif["Tahun"] == tahun_pilih]["Jumlah Mahasiswa"].sum()
aktif_prev = df_aktif[df_aktif["Tahun"] == tahun_sebelumnya]["Jumlah Mahasiswa"].sum()
col1.metric(
    label="Mahasiswa Aktif",
    value=f"{aktif_now:,}",
    delta=f"{aktif_now - aktif_prev:,}" if not pd.isna(aktif_prev) else "Data N/A"
)

# --- Lulusan ---
lulusan_now = df_lulusan[df_lulusan["Tahun"] == tahun_pilih]["Jumlah Lulusan"].sum()
lulusan_prev = df_lulusan[df_lulusan["Tahun"] == tahun_sebelumnya]["Jumlah Lulusan"].sum()
col2.metric(
    label="Lulusan Tahun Ini",
    value=f"{lulusan_now:,}",
    delta=f"{lulusan_now - lulusan_prev:,}" if not pd.isna(lulusan_prev) else "Data N/A"
)

# --- Prodi Aktif ---
total_prodi_now = df_prodi["Jumlah Prodi Aktif"].sum()  # anggap tetap (jika tidak per tahun)
col3.metric("Program Studi Aktif", total_prodi_now)

# === Jumlah Mahasiswa Aktif ===
st.subheader("Jumlah Mahasiswa Aktif per Program Studi")

aktif = df_aktif[df_aktif["Tahun"] == tahun_pilih]
if prodi_pilih != "Semua":
    aktif = aktif[aktif["Program Studi"] == prodi_pilih]

st.bar_chart(data=aktif, x="Program Studi", y="Jumlah Mahasiswa")

# === Lulusan per Semester ===
st.subheader("Jumlah Lulusan per Semester")

lulusan = df_lulusan[df_lulusan["Tahun"] == tahun_pilih]
if prodi_pilih != "Semua":
    lulusan = lulusan[lulusan["Program Studi"] == prodi_pilih]

# Buat grouped bar chart dengan Plotly
fig_lulusan = px.bar(
    lulusan,
    x="Program Studi",
    y="Jumlah Lulusan",
    color="Semester",
    barmode="group",
    title=f"Jumlah Lulusan Semester Ganjil/Genap - Tahun {tahun_pilih}"
)

st.plotly_chart(fig_lulusan, use_container_width=True)

# === Waktu Tempuh Studi ===
st.subheader("Rata-rata Waktu Tempuh Studi (Tahun)")
st.dataframe(df_waktu)

# === Status Akreditasi ===
st.subheader("Status Akreditasi Program Studi")
st.dataframe(df_akreditasi)

# === Jumlah Prodi Aktif ===
st.subheader("Jumlah Program Studi Aktif per Jenjang")
st.bar_chart(data=df_prodi, x="Jenjang", y="Jumlah Prodi Aktif")

import plotly.express as px

# === Jumlah Mahasiswa ===
st.subheader("Jumlah Mahasiswa per Jenjang dan Tahun")

distribusi = df_distribusi[df_distribusi["Tahun"] == tahun_pilih]

fig_pie = px.pie(
    distribusi,
    names="Jenjang",
    values="Jumlah Mahasiswa",
    title=f"Distribusi Mahasiswa Tahun {tahun_pilih}",
    hole=0.4  # jika ingin tampil seperti donut chart
)

st.plotly_chart(fig_pie, use_container_width=True)

# === Kuesioner Dosen ===
st.subheader("Rata-rata Skor Penilaian Dosen oleh Mahasiswa")
kues = df_kuesioner[df_kuesioner["Tahun"] == tahun_pilih]
st.bar_chart(data=kues, x="Program Studi", y="Rata-rata Skor Penilaian Dosen (1-5)")


st.caption("Sumber data: Simulasi internal")
